<b>Lab 01: Numpy</b></br>
MSSV: 20127030.</br>
Họ và tên: Nguyễn Mạnh Hùng.

Bài lab này được cài đặt trên jupyter notbook với phiên bản conda python 3.9.15 và phiên bản numpy là 1.21.5

In [1]:
import numpy as np
np.__version__

'1.21.5'

Ở bài lab này, mình đã cài đặt toàn bộ các phần sau:</br>
<ul>
  <li>Mean, Median, Max, Min, Range - Hoàn thành:100% </li>
  <li>Variance, Standard Deviation - Hoàn thành:100% </li>
  <li>Correlation matrix, Covariance matrix - Hoàn thành:100% </li>
  <li>Bonus: Handle with NaN - Hoàn thành:100% </li>
</ul>
<b><i>Lưu ý: tất cả các hàm đều được cài tay và so sánh kết quả với hàm có sẵn trong thư viên numpy và toàn bộ các mảng 2 chiều thể hiện biểu thức đa biến với mỗi biến được biểu diễn theo vector cột tương ứng </i></b>

<i><b>Chú thích: các biến tham số truyền vào hàm như sau:</b></i></br>
arr: tham số truyền vào là mảng, có thể là 1-D hay 2-D.</br>
col: tham số truyền vào là cột, vì ở đây các biến trong mảng đa biến đều được biểu diễn theo vector cột</br>
axis = 0: tham số truyền vào để tính các hàm trong hàm thư viện, tính các biến theo ma vector cột.</br>
Ngoài ra, trường hợp axis = 1 dùng để tính toán giá trị tương ứng với hàm truyền vào theo ma trận vector dòng. Nhưng do đề bài ta chỉ thiết lập các biến theo ma trận cột nên ta chỉ cần truyền tham số axis = 0.</br>

In [2]:
# tạo ra 2 sample để test các hàm.
               #X1 #X2 => cột một là biểu diễn X1, cột 2 là biểu diễn cho X2
A1 = np.array([[42, 4], 
               [52, 5], 
               [48, 4], 
               [58, 3]])
A2 = np.array([2, 10, 20, 9, 35, 48, 108, 69, 57])
# khi gặp các giá trị nan trong mảng thì thay giá trị đó = 0

# Sample Mean

Ta lần lượt cài đặt hàm tính trung bình các giá trị cho các mảng một chiều và 2 chiều.</br>
Ý tưởng: mean = (x1+x2+...+xn)/n 

In [3]:
# sample mean for 1-D array (parameter: an 1-D array)
def sample_mean(arr):
    result = arr.sum()/len(arr)
    return result

In [4]:
# sample mean for 2-D array with specific axis (parameter: column value, 2-D array)
def sample_mean_2D(arr, col):
    result = np.array(arr[:,col])
    mean = sample_mean(result)
    return mean

Thực hiện tính toán các hàm đã cài đặt

In [5]:
mean_A2 = sample_mean(A2)
mean_A1_col1 = sample_mean_2D(A1,0) # tính mean cho biến đầu tiên
mean_A1_col2 = sample_mean_2D(A1,1) # tính mean cho biến thứ 2

dùng hàm thư viện để đối chứng so sánh với hàm thủ công

In [6]:
m_A2 = np.mean(A2)
m_A1 = np.mean(A1,axis=0) # set axis = 0 để tính mean theo cột vì các biến được quy định là biểu diễn theo cột

<b> So sánh đối chiếu kết quả</b></br>
Ta lần lượt in 2 cột kết quả với cột đầu tiên là kết quả thủ công và cột thứ 2 là kết quả của hàm thư viện

In [7]:
print('Kết quả thủ công và Kết quả gọi hàm')
print('Mean A2: ', mean_A2, m_A2)
print('Mean A1 của biến 1: ', mean_A1_col1, m_A1[0])
print('Mean A1 của biến 2: ', mean_A1_col2, m_A1[1])

Kết quả thủ công và Kết quả gọi hàm
Mean A2:  39.77777777777778 39.77777777777778
Mean A1 của biến 1:  50.0 50.0
Mean A1 của biến 2:  4.0 4.0


Như vậy, ta có thể thấy là các hàm cài đặt thủ công đã tính đúng so với hàm thư viện.

# Mean Vector

Kế đến ta sẽ tính tiếp mean vector của các ma trận đã nêu ở trên.

In [8]:
# cài đặt hàm tính mean vector
def create_MeanVec(arr):
    size = len(arr[0])
    mean_vec = [0.0 for i in range(size)]
    for i in range (size):
        mean_vec[i] = sample_mean_2D(arr, col = i)
    return np.array(mean_vec)

Ta thực hiện tính mean vector đối với A1 sau đó đối chiếu với hàm thư viện.</br>
<b>Note:</b> khi gọi hàm np.mean(arr,axis=0) thì kết quả trả về là mean vector với các giá trị mean lần lượt của các biến có trong arr.</br> Cụ thể mean_vect of arr = [mean(X1)| mean(X2)|...| mean(Xn)] với X1, X2,..., Xn là các vector cột của các biến có trong arr 

In [9]:
mean_vector = create_MeanVec(A1)
print('So sánh: mean_vector và m_A1')
print('Mean vector (mean_vector)')
print(mean_vector)
print('hàm thư viện (m_A1)')
print(m_A1)

So sánh: mean_vector và m_A1
Mean vector (mean_vector)
[50.  4.]
hàm thư viện (m_A1)
[50.  4.]


<b> Như vậy ta có thể thấy được hàm thủ công và hàm thư viện đều cho ra các kết quả giống nhau </b>

# Sample Median

cài hàm thủ công tính median</br>
Ý tưởng: ta sắp xếp mảng theo thứ tự tăng dần và sau đó lấy giá trị trung tâm nếu số lượng ptu là lẻ, trường hợp số lượng là chẵn thì ta sẽ lấy trung bình 2 phần tử trung tâm mảng 

In [10]:
def median(arr):
    a = np.sort(arr)
    middle = int(len(a)/2)
    if (len(a)%2 == 1):
        return a[middle]
    else :
        return (a[middle-1] + a[middle]) / 2

Hàm tính median cho 1 biến cụ thể (vector cột)

In [11]:
def median_2D(arr, col):
    val = np.array(arr[:,col])
    result = median(val)
    return result

Tính các phép tính trên hàm thủ công và so sánh với hàm thư viện


In [12]:
A2_med = median(A2)
median_A2 = np.median(A2)
value = np.sort(A2)
print(value)
print('Kết quả hàm thủ công:', A2_med)
print('Kết quả hàm thư viện:', median_A2)

[  2   9  10  20  35  48  57  69 108]
Kết quả hàm thủ công: 35
Kết quả hàm thư viện: 35.0


In [13]:
A1_med = median_2D(A1, 0)
median_A1 = np.median(A1, axis = 0) # tính median theo cột
value = np.sort(A1[:,0])
print(value)
print('Kết quả hàm thủ công:',A1_med)
print('Kết quả hàm thư viện:',median_A1[0])

[42 48 52 58]
Kết quả hàm thủ công: 50.0
Kết quả hàm thư viện: 50.0


Ta thấy, hàm thủ công đã trả về kết quả lần lượt là 35 đối với A2 và 50 đối với A1 - lúc xét trên cột 1, biến X1</br>
Các giá trị trong mảng sẽ được sắp xếp theo giá trị tăng dần.</br>
<i>Ngoài ra, khi dùng hàm thư viện np.median(arr, axis = 0), kết quả trả về sẽ là một vector median của các biến có trong mảng.</i>

# Median vector

Kế đến ta sẽ tính vector median của A1

In [14]:
def create_MedianVec(arr): # hàm thủ công
    size = len(arr[0])
    median_vec = [0.0 for i in range(size)]
    for i in range (size):
        median_vec[i] = median_2D(arr, col = i)
    return np.array(median_vec)

Ta thực hiện tính median vector đối với A1 sau đó đối chiếu với hàm thư viện.</br>
<b>Note:</b> khi gọi hàm np.median(arr,axis=0) thì kết quả trả về là median vector với các giá trị median lần lượt của các biến có trong arr.</br> Cụ thể median_vect of arr = [median(X1)| median(X2)| ... | median(Xn)] với X1, X2,..., Xn là các vector cột của các biến có trong arr 

In [15]:
median_vector = create_MedianVec(A1)
print('So sánh: median_vector và median_A1')
print('Mean vector (median_vector)')
print(median_vector)
print('hàm thư viện (median_A1)')
print(median_A1)

So sánh: median_vector và median_A1
Mean vector (median_vector)
[50.  4.]
hàm thư viện (median_A1)
[50.  4.]


<b> Kết luận: 2 hàm đều cho ra kết quả giống nhau</b>

# Max và Min

Tại đây, ta sẽ tính các giá trị maximum và giá trị minimum của từng biến.

Cài đặt thủ công hàm max và hàm min

In [16]:
def Max(arr): # hàm max với tham số truyền vào là mảng
    result = -np.inf
    for i in range (len(arr)):
        if arr[i] > result:
            result = arr[i]
    return result

In [17]:
def Min(arr): # hàm min với tham số truyền vào là mảng
    result = np.inf
    for i in range (len(arr)):
        if arr[i] < result:
            result = arr[i]
    return result

Tính toán và so sánh với hàm thư viện

In [18]:
A2_max = Max(A2)
A2_min = Min(A2)
min = np.min(A2) # hàm thư viện
max = np.max(A2) # hàm thư viện

In [19]:
print('So sánh kết quả giữa 2 hàm trong A2')
print('Min: ', A2_min, min)
print('Max: ', A2_max, max)

So sánh kết quả giữa 2 hàm trong A2
Min:  2 2
Max:  108 108


<b> Qua trên, ta thấy các giá trị giữa các hàm thủ công và thư viện đều cho các kết quả giống nhau.

Tìm giá trị min max của mỗi biến trong mảng đa biến A1

In [20]:
def multi_Max(arr, col):
    val = np.array(arr[:,col])
    result = Max(val)
    return result

In [21]:
def multi_Min(arr, col):
    val = np.array(arr[:,col])
    result = Min(val)
    return result

Tính toán và so sánh kết quả đối chứng

In [22]:
A1_min = np.array([multi_Min(A1,0), multi_Min(A1,1)])
A1_max = np.array([multi_Max(A1,0), multi_Max(A1,1)])
max_A1 = np.max(A1,axis=0) # hàm thư viện
min_A1 = np.min(A1,axis=0) # hàm thư viện

In [23]:
print('So sánh kết quả giữa 2 hàm trong A1')
print('Min: ', A1_min, min_A1)
print('Max: ', A1_max, max_A1)

So sánh kết quả giữa 2 hàm trong A1
Min:  [42  3] [42  3]
Max:  [58  5] [58  5]


Kết quả trình bày theo dạng</br>
Min: Min của x1,x2(hàm thủ công) Min của x1,x2(hàm thư viện)</br>
Max: Max của x1,x2(hàm thủ công) Max của x1,x2(hàm thư viện)

<b> Kết luận: hàm thủ công và thư viện đều cho ra cùng 1 kết quả</b>

# Range

Ý tưởng: ta lấy giá trị Max - giá trị Min tương ứng với từng dòng đối với đa biến. Riêng trường hợp đơn biến chỉ lấy Max - Min

Cài đặt hàm thủ công.

In [24]:
def Range(arr):
    val = Max(arr) - Min(arr)
    return val

Cài đặt tính range cho trường hợp đa biến.

In [25]:
def Range_2D(arr,col):
    a = arr[:,col]
    val = Max(a) - Min(a)
    return val

Chạy và đối xứng giá trị

In [26]:
print('Hàm thư viện')
value = np.ptp(A1, axis=0) # value này trả về mảng giá trị tương ứng với [range(X1), range(X2)]
print("Vùng của X1 = ", value[0])
print("Vùng của X2 = ", value[1])
print('Hàm thủ công')
print("Vùng của X1 = ", Range_2D(A1,0))
print("Vùng của X2 = ", Range_2D(A1,1))

Hàm thư viện
Vùng của X1 =  16
Vùng của X2 =  2
Hàm thủ công
Vùng của X1 =  16
Vùng của X2 =  2


<b> Kết luận: 2 hàm đều cho kết quả như nhau</b>

# Variance


Cài đặt hàm thủ công tính phương sai variance</br>
Ý tưởng: tính theo công thức (1/n)*(sum((xi - mean of x)^2)), với i = 1,...,n

Hàm tính variance đơn biến

In [27]:
def Variance_1D(arr):
    sum = np.float32(0)
    mean_val = sample_mean(arr)
    for i in range(len(arr)):
        sum += (arr[i] - mean_val)**2
    sum /= len(arr)
    return sum

Hàm tính Variance đa biến

In [28]:
def Variance(arr, col):
    var = arr[:, col]
    sum = Variance_1D(var)
    return sum

Thực nghiệm và so sánh

Đơn biến

In [29]:
A2_var = Variance_1D(A2) # hàm tự cài
var_A2 = np.var(A2) # hàm thư viện

In [30]:
print('Phương sai của đơn biến A2: ', A2_var, var_A2)

Phương sai của đơn biến A2:  1060.8395061728397 1060.8395061728397


Đa biến

In [31]:
A1_var = np.array([Variance(A1,0), Variance(A1,1)]) # hàm tự cài
var_A1 = np.var(A1,axis = 0) # hàm thư viện

In [32]:
print('Phương sai của đa biến A1 theo format [var(X1), var(X2)]: ', A1_var, var_A1)

Phương sai của đa biến A1 theo format [var(X1), var(X2)]:  [34.   0.5] [34.   0.5]


<b> Kết luận: như vậy các hàm tự cài và hàm thư viện đều cho ra 2 kết quả giống nhau</b>

# Standard Deviation

Cài đặt hàm tính độ lệch chuẩn thủ công</br>
Ý tưởng: lấy căn bậc 2 của variance

Độ lệch chuẩn đơn biến

In [33]:
def STD(arr):
    value = Variance_1D(arr)
    return value**0.5

Độ lệch chuẩn đa biến

In [34]:
def STD_2D(arr, col):
    value = Variance(arr, col)
    return value**0.5

Kiểm nghiệm và so sánh kết quả với hàm thư viện

Đơn biến

In [35]:
A2_std = STD(A2) # hàm tự cài
standard_A2 = np.std(A2) # hàm thư viện

In [36]:
print('Độ lệch chuẩn của đơn biến A2: ', A2_std, standard_A2)

Độ lệch chuẩn của đơn biến A2:  32.57053125407751 32.57053125407751


Đa biến

In [37]:
A1_std = np.array([STD_2D(A1, 0), STD_2D(A1, 1)]) # hàm tự cài
standard_A1 = np.std(A1, axis=0) # hàm thư viện

In [38]:
print('Độ lệch chuẩn của đa biến A1 theo format [var(X1), var(X2)]: ', A1_std, standard_A1)

Độ lệch chuẩn của đa biến A1 theo format [var(X1), var(X2)]:  [5.83095189 0.70710678] [5.83095189 0.70710678]


<i>Kết luận: Các hàm thủ công đối với đơn biến và đa biến đều cho ra các kết quả giống nhau

# Covariance matrix

Tính ma trận covariance của dữ liệu đa biến.</br>
Ý tưởng: Sij = (1/n).sum[(xji - mean(xi)).(xjk - mean(xk))], với i,k = 1,2,...,p và Sij = Sji

hàm tính Covariance

In [39]:
def Covariance(arr, i, k):
    length = len(arr)
    sum = np.float32(0)
    mean_vector = np.mean(arr, axis=0)

    for j in range(length):
        sum += (arr[j][i] - mean_vector[i]) * (arr[j][k] - mean_vector[k])

    return sum / length

Hàm tạo ma trận Covariance

In [40]:
def createCovMatrix(arr):
    size = len(arr[0])
    cov_matrix = np.zeros((size, size))
    for i in range(size):
        for j in range(size):
            if cov_matrix[i][j] == 0:
                if i != j:
                    cov_matrix[i][j] = cov_matrix[j][i] = Covariance(arr, i, j)
                else:
                    cov_matrix[i][j] = Covariance(arr, i, j)
    return cov_matrix

Tính toán và so sánh, set rowvar = False để cho hàm thư viện hiểu là ma trận có biến biểu diễn dạng cột.

In [41]:
A1_cov = createCovMatrix(A1) # hàm thủ công
cov_A1 = np.cov(A1, rowvar=False, bias=True) # hàm thư viện

In [42]:
print('Ma trận hiệp phương sai của hàm thủ công')
print(A1_cov)
print('Ma trận hiệp phương sai của hàm thư viện')
print(cov_A1)

Ma trận hiệp phương sai của hàm thủ công
[[34.  -1.5]
 [-1.5  0.5]]
Ma trận hiệp phương sai của hàm thư viện
[[34.  -1.5]
 [-1.5  0.5]]


<b> Kết luận: 2 hàm đều cho ra kết quả giống nhau và ma trận này có các giá trị trên đường chéo chính bằng với phương sai tương ứng của mỗi biến</b>

# Correlation matrix

Ý tưởng: rik = Sik / ((Sii^0.5)*(Skk^0.5)), với i,k = 1,2,...,p và Sik, Sii, Skk là hệ số hiệp phương sai covariance.</br>
Tính chất: rik = rki

Cài đặt hàm thủ công tính toán hệ số tương quan. Set rowvar = False để cho hàm thư viện hiểu là ma trận có biến biểu diễn dạng cột

In [43]:
def Correlation_coefficient(Sik, Sii, Skk):
    return Sik/((Sii**0.5)*(Skk**0.5))

Cài đặt hàm tính ma trận correlation

In [44]:
def Correlation_matrix(arr):
    size = len(arr[0])
    corr = np.zeros((size, size))
    for i in range(size):
        for j in range(size):
            corr[i, j] = Correlation_coefficient(arr[i, j], arr[i, i], arr[j, j])
    return corr

Tạo ma trận hệ số tương quan cho A1 và đối chiếu với hàm thư viện

In [45]:
A1_corr = Correlation_matrix(np.cov(A1,rowvar=False, bias=True)) # hàm cài tay
corr_A1 = np.corrcoef(A1,rowvar=False) # hàm thư viện

In [46]:
print('Ma trận hệ số tương quan của hàm thủ công')
print(A1_corr)
print('Ma trận hệ số tương quan của hàm thư viện')
print(corr_A1)

Ma trận hệ số tương quan của hàm thủ công
[[ 1.         -0.36380344]
 [-0.36380344  1.        ]]
Ma trận hệ số tương quan của hàm thư viện
[[ 1.         -0.36380344]
 [-0.36380344  1.        ]]


<b> Kết luận: 2 hàm đều cho ra kết quả giống nhau.</b>

# Bonus: Handle with NaN

Dữ liệu NaN là một giá trị của kiểu dữ liệu số, biểu diễn một giá trị không xác định hoặc không thể biểu diễn.</br>
Trong tính toán thông thường khi gặp các kiểu dữ liệu kiểu này thì rất khó để giải quyết và tính toán.</br>
Như vậy có 2 cách để giải quyết khi gặp vấn đề này:
<ul>
  <li>Loại bỏ các giá trị đó bằng cách gán chúng bằng 0, sau đó dùng hàm thủ công đã cài đặt để làm</li>
  <li>Áp dụng hàm thư viện có sẵn để tính</li>
</ul>
Chúng ta lần lượt đi từng bước để kiểm nghiệm đối chứng kết quả giữa 2 cách trên.

Giả sử ta có tập dữ liệu tồn tại các giá trị NaN như sau:

In [47]:
# tương tự A1 và A2, ta khởi tạo A3 và A4
A3 = np.array([[14, 96],
               [np.nan, 82],
               [80, 67],
               [77, np.nan],
               [99, 87]])

A4 = np.array([2, np.nan, 5, 9])

<b>Tính toán thủ công lọc các giá trị NaN</b>

In [48]:
def remove_nan(arr):
    mask = np.isnan(arr)
    arr[mask] = 0 # set giá trị = 0 để làm mốc cho NaN
    return arr

In [49]:
A3_nonNaN = remove_nan(A3)
A4_nonNaN = A4[np.isfinite(A4)]

Lúc này kết quả sau khi lọc NaN của A3 và A4 là

In [50]:
print(A3_nonNaN)
print(A4_nonNaN)

[[14. 96.]
 [ 0. 82.]
 [80. 67.]
 [77.  0.]
 [99. 87.]]
[2. 5. 9.]


Tách các biến của dữ liệu nhiều biến A3

In [51]:
A3_nonNaN_1 = A3_nonNaN[:,0]
A3_nonNaN_1 = np.delete(A3_nonNaN_1, np.where(A3_nonNaN_1 == 0)) # xóa đi các giá trị mốc = 0
A3_nonNaN_2 = A3_nonNaN[:,1]
A3_nonNaN_2 = np.delete(A3_nonNaN_2, np.where(A3_nonNaN_2 == 0)) # xóa đi các giá trị mốc = 0

<i> Đơn biến</i>

In [52]:
print('Hàm thủ công cho A4')
print("mean_A4 = ", sample_mean(A4_nonNaN))
print("median_A4 = ", median(A4_nonNaN))
print("variance_A4 = ", Variance_1D(A4_nonNaN))
print("std_A4 = ", STD(A4_nonNaN))

Hàm thủ công cho A4
mean_A4 =  5.333333333333333
median_A4 =  5.0
variance_A4 =  8.222222222222221
std_A4 =  2.8674417556808756


So sánh với hàm thư viện

In [53]:
print('Hàm thư viện cho A4')
print("mean_A4 = ", np.nanmean(A4))
print("median_A4 = ", np.nanmedian(A4))
print("variance_A4 = ", np.nanvar(A4))
print("std_A4 = ", np.nanstd(A4))

Hàm thư viện cho A4
mean_A4 =  5.333333333333333
median_A4 =  5.0
variance_A4 =  8.222222222222221
std_A4 =  2.8674417556808756


<i>Nhiều biến</i>

<b>Lưu ý: format output là [cal(X1), cal(X2)], với cal là các hàm tính toán thông số của X1 và X2</b>

In [54]:
print('Hàm thủ công cho A3')
print("mean_A3 = ", [sample_mean(A3_nonNaN_1), sample_mean(A3_nonNaN_2)])
print("median_A3 = ", [median(A3_nonNaN_1), median(A3_nonNaN_2)])
print("variance_A3 = ", [Variance_1D(A3_nonNaN_1), Variance_1D(A3_nonNaN_2)])
print("std_A3 = ", [STD(A3_nonNaN_1), STD(A3_nonNaN_2)])

Hàm thủ công cho A3
mean_A3 =  [67.5, 83.0]
median_A3 =  [78.5, 84.5]
variance_A3 =  [1025.25, 110.5]
std_A3 =  [32.01952529317073, 10.51189802081432]


So sánh với hàm thư viện

In [55]:
print('Hàm thư viện cho A3')
print("mean_A3 = ", np.nanmean(A3,axis=0))
print("median_A3 = ", np.nanmedian(A3,axis=0))
print("variance_A3 = ", np.nanvar(A3,axis=0))
print("std_A3 = ", np.nanstd(A3,axis=0))

Hàm thư viện cho A3
mean_A3 =  [54.  66.4]
median_A3 =  [77. 82.]
variance_A3 =  [1549.2  1190.64]
std_A3 =  [39.35987805 34.50565171]


<b> Kết luận: sau khi làm thủ công và so sánh với hàm thư viện, ta thấy các hàm thư viện bỏ qua các giá trị NaN và tính toán trên toàn bộ các giá trị thực. Đồng thời 2 hàm đều cho ra kết quả giống nhau.</b>

# Các trang tham khảo

<ul>
  <li>Tài liệu + slide của thầy Lý Quốc Ngọc</li>
  <li>Tài liệu của thầy Hùng</li>
  <li>https://stackoverflow.com/questions/29438329/removing-nans-from-numpy-2-d-arrays</li>
  <li>https://stackoverflow.com/questions/14657433/correlation-matrix-in-python</li>
  <li>https://vietnambiz.vn/do-lech-chuan-standard-deviation-la-gi-cong-thuc-tinh-do-lech-chuan-2019110216112891.htm</li>
</ul>