In [1]:
import torch
import pandas as pd
import numpy as np

from fc_layer import FCLayer 
from act_layer import ActivationLayer
from activation import Activation
from activation_prime import ActivationPrime
from loss import Loss
from loss_prime import LossPrime
from network import Network

Đọc dữ liệu từ file data.csv

In [2]:
x_train = pd.read_csv('data.csv', usecols=[0,1,2]) # Read first 3 variable columns in dataset
x_train = x_train.values.tolist() # Convert dataframe to list

y_train = pd.read_csv('data.csv', usecols=[3]) # Read result columns in dataset
y_train = y_train.values.tolist() # Convert dataframe to list

Dữ liệu của file data.csv

In [3]:
for i in range(len(x_train)):
    print("#"+str(i+1)+": "+str(x_train[i])+" "+str(y_train[i]))

#1: [44.5, 39.3, 45.1] [10.4]
#2: [17.2, 45.9, 69.3] [12.0]
#3: [151.5, 41.3, 58.5] [16.5]
#4: [180.8, 10.8, 58.4] [17.9]
#5: [8.7, 48.9, 75.0] [7.2]
#6: [57.5, 32.8, 23.5] [11.8]
#7: [120.2, 19.6, 11.6] [13.2]
#8: [8.6, 2.1, 1.0] [4.8]
#9: [199.8, 2.6, 21.2] [15.6]
#10: [66.1, 5.8, 24.2] [12.6]
#11: [214.7, 24.0, 4.0] [17.4]
#12: [23.8, 35.1, 65.9] [9.2]
#13: [97.5, 7.6, 7.2] [13.7]
#14: [204.1, 32.9, 46.0] [19.0]
#15: [195.4, 47.7, 52.9] [22.4]
#16: [67.8, 36.6, 114.0] [12.5]
#17: [281.4, 39.6, 55.8] [24.4]
#18: [69.2, 20.5, 18.3] [11.3]
#19: [147.3, 23.9, 19.1] [14.6]
#20: [218.4, 27.7, 53.4] [18.0]
#21: [237.4, 5.1, 23.5] [17.5]
#22: [13.2, 15.9, 49.6] [5.6]
#23: [228.3, 16.9, 26.2] [20.5]
#24: [62.3, 12.6, 18.3] [9.7]
#25: [262.9, 3.5, 19.5] [17.0]
#26: [142.9, 29.3, 12.6] [15.0]
#27: [240.1, 16.7, 22.9] [20.9]
#28: [248.8, 27.1, 22.9] [18.9]
#29: [70.6, 16.0, 40.8] [10.5]
#30: [292.9, 28.3, 43.2] [21.4]
#31: [112.9, 17.4, 38.6] [11.9]
#32: [97.2, 1.5, 30.0] [13.2]
#33: [265.6, 20

Set up dữ liệu để train

In [4]:
# training data
x_trainset = list()
y_trainset = list()
for i in range(80):
    x_temp = list()
    x_temp.append(x_train[i])
    x_max = max(x_train[i])
    x_edit = [[x / x_max for x in x_temp[0]]]
    x_trainset.append(x_edit)

    y_temp = list()
    y_temp.append(y_train[i])
    y_edit = [[y / 100 for y in y_temp[0]]]
    y_trainset.append(y_edit)

x_set = torch.tensor(x_trainset, dtype=torch.float)
y_set = torch.tensor(y_trainset, dtype=torch.float)

Set up mạng neural<br>
Bao gồm: <br>
+) Input layer: 3 perceptrons <br>
+) 1st Hidden layers: 15 perceptrons <br>
+) 2nd Hidden layers: 12 perceptrons <br>
+) Output layer: 1 perceptron <br>

In [5]:
# network architecture with tanh activation
net = Network()
net.add(FCLayer(3, 15))
net.add(ActivationLayer(Activation.tanh, ActivationPrime.tanh_derivative))
net.add(FCLayer(15, 12))
net.add(ActivationLayer(Activation.tanh, ActivationPrime.tanh_derivative))
net.add(FCLayer(12, 1))
net.add(ActivationLayer(Activation.tanh, ActivationPrime.tanh_derivative))

# train your network
net.use(Loss.mse, LossPrime.mse_prime)
net.fit(x_set, y_set, epochs=1400, alpha=0.01) # learning rate = 0.01

On epoch 1 an average error = tensor(0.2026)
On epoch 2 an average error = tensor(0.1172)
On epoch 3 an average error = tensor(0.0646)
On epoch 4 an average error = tensor(0.0331)
On epoch 5 an average error = tensor(0.0271)
On epoch 6 an average error = tensor(0.0245)
On epoch 7 an average error = tensor(0.0224)
On epoch 8 an average error = tensor(0.0206)
On epoch 9 an average error = tensor(0.0192)
On epoch 10 an average error = tensor(0.0179)
On epoch 11 an average error = tensor(0.0167)
On epoch 12 an average error = tensor(0.0157)
On epoch 13 an average error = tensor(0.0147)
On epoch 14 an average error = tensor(0.0138)
On epoch 15 an average error = tensor(0.0129)
On epoch 16 an average error = tensor(0.0121)
On epoch 17 an average error = tensor(0.0113)
On epoch 18 an average error = tensor(0.0106)
On epoch 19 an average error = tensor(0.0099)
On epoch 20 an average error = tensor(0.0092)
On epoch 21 an average error = tensor(0.0086)
On epoch 22 an average error = tensor(0.008

Prepare the dataset to test (included in data.csv)

In [6]:
def scaling(testcase):
    num = max(testcase)
    result = [[i / num for i in testcase]]
    return result

In [15]:
# test
testing = list()
case_1 = [[94.2, 4.9, 8.1]] # correct result 14.0
case_2 = [[17.2,4.1,31.6]] # correct result 5.9
case_3 = [[56.2,5.7,29.7]] # correct result 8.7

testcase_1 = scaling(case_1[0])
testing.append(testcase_1)

testcase_2 = scaling(case_2[0])
testing.append(testcase_2)

testcase_3 = scaling(case_3[0])
testing.append(testcase_3)

for i in range(len(testing)):
    print(testing[i])


[[1.0, 0.05201698513800425, 0.08598726114649681]]
[[0.5443037974683543, 0.12974683544303794, 1.0]]
[[1.0, 0.10142348754448398, 0.5284697508896796]]
[[1.0, 0.11357490535424554, 0.11898323418063818]]


In [16]:
# testing phase
data = torch.tensor(testing, dtype = torch.float)

out = net.predicts(data)
print(out)

[tensor([[0.1545]]), tensor([[0.2085]]), tensor([[0.0802]]), tensor([[0.1549]])]


Tạo model riêng

In [9]:
from My_Model import FFNN

Set up mạng neural tự tạo<br>
Bao gồm: <br>
+) Input layer: 3 perceptrons <br>
+) 1st Hidden layers: 12 perceptrons <br>
+) 2nd Hidden layers: 12 perceptrons <br>
+) Output layer: 1 perceptron <br>

In [10]:
# training data for my model
train_x = torch.tensor(x_train[:80], dtype=torch.float)
train_y = torch.tensor(y_train[:80], dtype=torch.float)

# scale units by max value
X_max, _ = torch.max(train_x, 0)
train_x = torch.div(train_x, X_max)
train_y = train_y / 100  # for max test score is 100

In [17]:
# testing case
predict_case1 = torch.tensor(([94.2, 4.9, 8.1]), dtype=torch.float) # correct result 14.0
predict_case2 = torch.tensor(([17.2,4.1,31.6]), dtype=torch.float) # correct result 5.9
predict_case3 = torch.tensor(([56.2,5.7,29.7]), dtype=torch.float) # correct result 8.7


x_predict_max, _ = torch.max(predict_case1, 0)
predict_case1 = torch.div(predict_case1, x_predict_max)

x_predict_max, _ = torch.max(predict_case2, 0)
predict_case2 = torch.div(predict_case2, x_predict_max)

x_predict_max, _ = torch.max(predict_case3, 0)
predict_case3 = torch.div(predict_case3, x_predict_max)

print(predict_case1)
print(predict_case2)
print(predict_case3)

tensor([1.0000, 0.0520, 0.0860])
tensor([0.5443, 0.1297, 1.0000])
tensor([1.0000, 0.1014, 0.5285])


Runing model

In [12]:
# initialize own built model 
mymodel = FFNN()
mymodel.fit(train_x, train_y, 1400, lr = 0.01)

Epoch #0 MSE Loss: tensor(0.0102)
Epoch #1 MSE Loss: tensor(0.0091)
Epoch #2 MSE Loss: tensor(0.0082)
Epoch #3 MSE Loss: tensor(0.0075)
Epoch #4 MSE Loss: tensor(0.0070)
Epoch #5 MSE Loss: tensor(0.0065)
Epoch #6 MSE Loss: tensor(0.0062)
Epoch #7 MSE Loss: tensor(0.0058)
Epoch #8 MSE Loss: tensor(0.0056)
Epoch #9 MSE Loss: tensor(0.0054)
Epoch #10 MSE Loss: tensor(0.0052)
Epoch #11 MSE Loss: tensor(0.0050)
Epoch #12 MSE Loss: tensor(0.0049)
Epoch #13 MSE Loss: tensor(0.0048)
Epoch #14 MSE Loss: tensor(0.0047)
Epoch #15 MSE Loss: tensor(0.0046)
Epoch #16 MSE Loss: tensor(0.0045)
Epoch #17 MSE Loss: tensor(0.0044)
Epoch #18 MSE Loss: tensor(0.0044)
Epoch #19 MSE Loss: tensor(0.0043)
Epoch #20 MSE Loss: tensor(0.0043)
Epoch #21 MSE Loss: tensor(0.0042)
Epoch #22 MSE Loss: tensor(0.0042)
Epoch #23 MSE Loss: tensor(0.0041)
Epoch #24 MSE Loss: tensor(0.0041)
Epoch #25 MSE Loss: tensor(0.0041)
Epoch #26 MSE Loss: tensor(0.0041)
Epoch #27 MSE Loss: tensor(0.0040)
Epoch #28 MSE Loss: tensor(0.0

Test result

In [13]:
mymodel.predict(predict_case1)
mymodel.predict(predict_case2)
mymodel.predict(predict_case3)

Predict: tensor([0.1212])
Predict: tensor([0.1719])
Predict: tensor([0.1601])
